import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const sans = Oswald({ subsets: ["latin", "vietnamese"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/kdb.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={sans.className}>
      <body className={`antialiased dark`}>{children} </body>
    </html>
  );
}
